export interface AlertRule {
    name: string;
    pattern: RegExp;
    priority: "P1" | "P2" | "P3";
    severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
    summary: string;
    description: string;
}

export const defaultRules: AlertRule[] = [
    {
        name: "Fatal Error",
        pattern: /\bFATAL\b|\bfatal error\b/i,
        priority: "P1",
        severity: "CRITICAL",
        summary: "Fatal error detected",
        description: "A fatal error was detected in the service logs.",
    },
    {
        name: "Out Of Memory",
        pattern: /out of memory|outofmemory|heap out of memory|memory limit exceeded/i,
        priority: "P1",
        severity: "CRITICAL",
        summary: "Out of memory",
        description: "An out-of-memory condition was detected.",
    },
    {
        name: "Container OOM Killed",
        pattern: /OOMKilled|oom kill|oom-killed/i,
        priority: "P1",
        severity: "CRITICAL",
        summary: "Container was OOM killed",
        description: "A container was terminated because it exceeded its memory limit.",
    },
    {
        name: "Database Connection Failed",
        pattern: /database connection failed|failed to connect.*database|database.*connection.*failed|database connection error/i,
        priority: "P1",
        severity: "CRITICAL",
        summary: "Database connection failed",
        description: "A database connection failure was detected.",
    },
    {
        name: "Database Unavailable",
        pattern: /database unavailable|db unavailable|database is down|db is down/i,
        priority: "P1",
        severity: "CRITICAL",
        summary: "Database unavailable",
        description: "The application reported that the database is unavailable.",
    },
    {
        name: "Service Unavailable",
        pattern: /service unavailable|503 service unavailable|service is unavailable/i,
        priority: "P1",
        severity: "CRITICAL",
        summary: "Service unavailable",
        description: "A service unavailable condition was detected.",
    },
    {
        name: "Health Check Failed",
        pattern: /health check failed|healthcheck failed|health check.*unhealthy|health endpoint.*failed/i,
        priority: "P1",
        severity: "CRITICAL",
        summary: "Health check failed",
        description: "A service health check failure was detected.",
    },
    {
        name: "Connection Refused",
        pattern: /connection refused|connect ECONNREFUSED|ECONNREFUSED/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Connection refused",
        description: "A connection refused error was detected.",
    },
    {
        name: "Connection Reset",
        pattern: /connection reset|ECONNRESET|socket hang up/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Connection reset",
        description: "An existing network connection was unexpectedly reset.",
    },
    {
        name: "Connection Timeout",
        pattern: /connection timeout|connect timed out|ETIMEDOUT|request timeout|request timed out/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Connection timeout",
        description: "A connection or request timeout was detected.",
    },
    {
        name: "DNS Resolution Failed",
        pattern: /DNS resolution failed|ENOTFOUND|getaddrinfo ENOTFOUND|name resolution failed/i,
        priority: "P2",
        severity: "HIGH",
        summary: "DNS resolution failed",
        description: "The service failed to resolve a hostname.",
    },
    {
        name: "Network Unreachable",
        pattern: /network unreachable|ENETUNREACH|EHOSTUNREACH|no route to host/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Network unreachable",
        description: "The service reported that the target network or host is unreachable.",
    },
    {
        name: "Authentication Failed",
        pattern: /authentication failed|auth failed|invalid credentials|invalid token|unauthorized|401 unauthorized/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Authentication failure",
        description: "An authentication failure was detected.",
    },
    {
        name: "Authorization Failed",
        pattern: /authorization failed|access denied|permission denied|forbidden|403 forbidden/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Authorization failure",
        description: "An authorization or permission failure was detected.",
    },
    {
        name: "Rate Limit Exceeded",
        pattern: /rate limit exceeded|too many requests|429 too many requests|rate_limit_exceeded/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Rate limit exceeded",
        description: "The service or an external API reported a rate limit violation.",
    },
    {
        name: "API Request Failed",
        pattern: /api request failed|request failed|http request failed|upstream request failed/i,
        priority: "P2",
        severity: "HIGH",
        summary: "API request failed",
        description: "An API or HTTP request failure was detected.",
    },
    {
        name: "Internal Server Error",
        pattern: /500 internal server error|internal server error|HTTP 500|\bstatus.?code.?500\b/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Internal server error",
        description: "An internal server error was detected.",
    },
    {
        name: "Bad Gateway",
        pattern: /502 bad gateway|bad gateway|HTTP 502/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Bad gateway",
        description: "A bad gateway response was detected.",
    },
    {
        name: "Gateway Timeout",
        pattern: /504 gateway timeout|gateway timeout|HTTP 504/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Gateway timeout",
        description: "A gateway timeout was detected.",
    },
    {
        name: "Exception",
        pattern: /\bException\b|UnhandledException|Unhandled exception/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Exception detected",
        description: "An unhandled exception was detected in the service logs.",
    },
    {
        name: "Unhandled Error",
        pattern: /uncaught exception|uncaught error|unhandled error|unhandled rejection|UnhandledPromiseRejection/i,
        priority: "P1",
        severity: "CRITICAL",
        summary: "Unhandled error detected",
        description: "An unhandled application error was detected.",
    },
    {
        name: "Traceback",
        pattern: /\bTraceback\b|stack trace/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Stack trace detected",
        description: "A stack trace or traceback was detected in the service logs.",
    },
    {
        name: "Application Error",
        pattern: /\bERROR\b|\bERR\b|\bERROR:/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Application error detected",
        description: "An application error was detected in the service logs.",
    },
    {
        name: "Critical Error",
        pattern: /\bCRITICAL\b|\bCRIT\b/i,
        priority: "P1",
        severity: "CRITICAL",
        summary: "Critical error detected",
        description: "A critical error was detected in the service logs.",
    },
    {
        name: "Database Query Failed",
        pattern: /query failed|database query failed|SQL error|query execution failed/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Database query failed",
        description: "A database query execution failure was detected.",
    },
    {
        name: "Deadlock Detected",
        pattern: /deadlock detected|deadlock found|transaction deadlock/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Database deadlock detected",
        description: "A database transaction deadlock was detected.",
    },
    {
        name: "Redis Connection Failed",
        pattern: /redis.*connection.*failed|failed to connect.*redis|redis.*ECONNREFUSED/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Redis connection failed",
        description: "A Redis connection failure was detected.",
    },
    {
        name: "Kafka Connection Failed",
        pattern: /kafka.*connection.*failed|failed to connect.*kafka|kafka.*broker.*unavailable/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Kafka connection failed",
        description: "A Kafka broker connection failure was detected.",
    },
    {
        name: "Message Queue Failure",
        pattern: /message queue.*failed|queue connection failed|queue unavailable|broker unavailable/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Message queue failure",
        description: "A message queue or broker failure was detected.",
    },
    {
        name: "File System Error",
        pattern: /file system error|filesystem error|disk I\/O error|EIO|ENOSPC/i,
        priority: "P2",
        severity: "HIGH",
        summary: "File system error",
        description: "A file system or disk I/O failure was detected.",
    },
    {
        name: "Disk Space Low",
        pattern: /disk space low|low disk space|disk full|no space left on device/i,
        priority: "P1",
        severity: "CRITICAL",
        summary: "Disk space critical",
        description: "The service reported insufficient disk space.",
    },
    {
        name: "Permission Denied",
        pattern: /permission denied|EACCES|EPERM/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Permission denied",
        description: "A file system or resource permission error was detected.",
    },
    {
        name: "Configuration Error",
        pattern: /configuration error|config error|invalid configuration|missing configuration/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Configuration error",
        description: "An invalid or missing application configuration was detected.",
    },
    {
        name: "Environment Variable Missing",
        pattern: /missing environment variable|environment variable.*not set|required environment variable/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Environment variable missing",
        description: "A required environment variable was not available.",
    },
    {
        name: "SSL Error",
        pattern: /SSL error|TLS error|certificate error|certificate has expired|CERT_HAS_EXPIRED/i,
        priority: "P2",
        severity: "HIGH",
        summary: "SSL/TLS error",
        description: "An SSL or TLS certificate error was detected.",
    },
    {
        name: "Memory Leak Warning",
        pattern: /memory leak|possible memory leak|heap usage critical/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Possible memory leak",
        description: "The service reported a possible memory leak.",
    },
    {
        name: "Process Crashed",
        pattern: /process crashed|process exited unexpectedly|application crashed|fatal signal/i,
        priority: "P1",
        severity: "CRITICAL",
        summary: "Process crashed",
        description: "An application process crash was detected.",
    },
    {
        name: "Container Stopped",
        pattern: /container stopped|container exited|container has stopped/i,
        priority: "P1",
        severity: "CRITICAL",
        summary: "Container stopped",
        description: "A monitored container stopped unexpectedly.",
    },
    {
        name: "Service Crashed",
        pattern: /service crashed|service terminated unexpectedly|service exited unexpectedly/i,
        priority: "P1",
        severity: "CRITICAL",
        summary: "Service crashed",
        description: "A monitored service terminated unexpectedly.",
    },
    {
        name: "Dependency Failure",
        pattern: /dependency unavailable|dependency failed|external service failed|upstream service unavailable/i,
        priority: "P2",
        severity: "HIGH",
        summary: "Dependency failure",
        description: "A dependency or upstream service failure was detected.",
    },
    {
    name: "Slow Response Time",
    pattern: /response time exceeded 2000ms/i,
    priority: "P2",
    severity: "MEDIUM",
    summary: "Slow Response Time",
    description: "Response time exceeded 2000ms",
},
];